# Generated by Django 3.1.7 on 2021-04-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210401_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ip',
            old_name='ip_utente',
            new_name='ip',
        ),
    ]
